### ISSUE TITLE
Feature Request: Download swarm_key to backup RAK hotspots with the app

### ISSUE THREAD

**Issue by Wheaties466** [helium/gateway-config#67]
It would be great if there was functionality built in to download the swarm key. Currently the only way to back up the swarm_key of the RAK hotspots is to create an image of the SD card. It would be way more user friendly if this had the ability to backup over bluetooth with the app.

**Comment by fvasquez** [comment]
I believe the RAKspots have an EEPROM that can be written to. This peripheral is on an I2C bus that needs to be enabled in the Helium Hotspot OTA image. A miner could save and read the swarm_key out of the EEPROM instead of the ECC608 (Helium Hotspots) for RAKspots. That's safer than sending your swarm_key over BLE to the mobile app. Otherwise someone with physical access to your RAKspot could steal your swarm_key.

**Comment by Wheaties466** [comment]
How would someone access the swarm_key once its saved to the EEPROM?

**Comment by fvasquez** [comment]
> How would someone access the swarm_key once its saved to the EEPROM?

They wouldn't need to access it. If the microSD wears out and gets replaced the RAKspot would keep its identity because the swarm_key is stored on the EEPROM just like the swarm_key is stored on the ECC608 for Helium Hotspots.

**Comment by madninja** [comment]
We're going to close this due to inactivity.
