### ISSUE TITLE
Issue: Unable to run pre hooks for 'compile', command 'compile' in namespace 'protobuf' not found.

### ISSUE THREAD

**Issue by ryanteck** [helium/gateway-config#68]
Just a quick issue I'm haivng when trying to compile this.

I seem to be facing the above error message " Unable to run pre hooks for 'compile', command 'compile' in namespace 'protobuf' not found." when running make.

Is there any ideas as to how to resolve this?

**Comment by ryanteck** [comment]
Resolved:

Originally installed erlang libraries one by one, however it seems I must have missed one out. Installing the debian package that installs a majority fixed it.

**Comment by fvasquez** [comment]
@ryanteck check out the [Dockerfile](https://github.com/helium/miner/blob/master/.buildkite/scripts/Dockerfile-arm64) that Helium uses to build and run the their [miner](/helium/miner). That Dockerfile relies on an Alpine base image that targets arm64 for the Raspberry Pi 3 and 4. That Alpine image comes with Erlang/OTP 22.3 installed. That Dockerfile invokes rebar3 directly instead of through the repo's top-level `Makefile`.

Ignore most of the weird native compilation flags in that Dockerfile. They are for RocksDB which `gateway_config` does not depend on. The `sed` commands also only apply to `miner`'s `sys.config`. The most important dependency besides the Erlang/OTP stuff is `dbus-dev` which `gateway_config` needs to build `ebus`.

I've seen `gpb` pollute the `_build` directory with bad BEAM files in the past. Add a [`.dockerignore`](https://github.com/helium/miner/blob/master/.buildkite/scripts/.dockerignore) to delete the `_build` directory so that subsequent builds don't keep failing with `protobuf`-related errors. The _Adopting Erlang_ book has lots of [good advice](https://adoptingerlang.org/docs/production/docker/) on how to use Docker to build Erlang projects.

**Comment by fvasquez** [comment]
> Resolved:
> 
> Originally installed erlang libraries one by one, however it seems I must have missed one out. Installing the debian package that installs a majority fixed it.

If it works don't fix it ;)
